In [4]:
import pandas as pd
import numpy as np

df = pd.read_csv("C:/Users/paolo/OneDrive/Desktop/Progetto finale/WA_Fn-UseC_-Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [5]:
print(df.shape)
df.info()

(7043, 21)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [6]:
new_names = {
    "customerID": "Customer ID",
    "gender": "Gender",
    "SeniorCitizen": "Senior Citizen",
    "Partner": "Has Partner",
    "Dependents": "Has Dependents",
    "tenure": "Tenure (Months)",
    "PhoneService": "Phone Service",
    "MultipleLines": "Multiple Lines",
    "InternetService": "Internet Service",
    "OnlineSecurity": "Online Security",
    "OnlineBackup": "Online Backup",
    "DeviceProtection": "Device Protection",
    "TechSupport": "Tech Support",
    "StreamingTV": "Streaming TV",
    "StreamingMovies": "Streaming Movies",
    "Contract": "Contract Type",
    "PaperlessBilling": "Paperless Billing",
    "PaymentMethod": "Payment Method",
    "MonthlyCharges": "Monthly Charges",
    "TotalCharges": "Total Charges",
    "Churn": "Attrition"
}

df = df.rename(columns=new_names)
df.head()

,Customer ID,Gender,Senior Citizen,Has Partner,Has Dependents,Tenure (Months),Phone Service,Multiple Lines,Internet Service,Online Security,...,Device Protection,Tech Support,Streaming TV,Streaming Movies,Contract Type,Paperless Billing,Payment Method,Monthly Charges,Total Charges,Attrition
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [7]:
print(df["Attrition"].value_counts())
print()
print(df["Attrition"].value_counts(normalize=True) * 100)

Attrition
No     5174
Yes    1869
Name: count, dtype: int64

Attrition
No     73.463013
Yes    26.536987
Name: proportion, dtype: float64

In [8]:
colonne_testo = df.select_dtypes(include="object").columns.drop(["Customer ID", "Total Charges"])

for col in colonne_testo:
    print(col, "->", df[col].unique().tolist())

Gender -> ['Female', 'Male']
Has Partner -> ['Yes', 'No']
Has Dependents -> ['No', 'Yes']
Phone Service -> ['No', 'Yes']
Multiple Lines -> ['No phone service', 'No', 'Yes']
Internet Service -> ['DSL', 'Fiber optic', 'No']
Online Security -> ['No', 'Yes', 'No internet service']
Online Backup -> ['Yes', 'No', 'No internet service']
Device Protection -> ['No', 'Yes', 'No internet service']
Tech Support -> ['No', 'Yes', 'No internet service']
Streaming TV -> ['No', 'Yes', 'No internet service']
Streaming Movies -> ['No', 'Yes', 'No internet service']
Contract Type -> ['Month-to-month', 'One year', 'Two year']
Paperless Billing -> ['Yes', 'No']
Payment Method -> ['Electronic check', 'Mailed check', 'Bank transfer (automatic)', 'Credit card (automatic)']
Attrition -> ['No', 'Yes']

In [9]:
data_dictionary = pd.DataFrame({
    "Column": df.columns,
    "Description": [
        "Unique customer identifier",
        "Customer gender (Female / Male)",
        "Whether the customer is a senior citizen (0 = No, 1 = Yes)",
        "Whether the customer has a partner",
        "Whether the customer has dependents",
        "Number of months the customer has been with the company",
        "Whether the customer has a phone service",
        "Whether the customer has multiple phone lines",
        "Type of internet service (DSL, Fiber optic, None)",
        "Whether the customer has online security add-on",
        "Whether the customer has online backup add-on",
        "Whether the customer has device protection add-on",
        "Whether the customer has tech support add-on",
        "Whether the customer streams TV through the company",
        "Whether the customer streams movies through the company",
        "Contract duration (Month-to-month, One year, Two year)",
        "Whether the customer receives electronic invoices",
        "How the customer pays the bill",
        "Amount charged to the customer every month",
        "Total amount charged to the customer over time",
        "Whether the customer left the company (target variable)"
    ],
    "Data Type": df.dtypes.astype(str).values
})

data_dictionary

,Column,Description,Data Type
0,Customer ID,Unique customer identifier,object
1,Gender,Customer gender (Female / Male),object
2,Senior Citizen,Whether the customer is a senior citizen (0 = ...,int64
3,Has Partner,Whether the customer has a partner,object
4,Has Dependents,Whether the customer has dependents,object
5,Tenure (Months),Number of months the customer has been with th...,int64
6,Phone Service,Whether the customer has a phone service,object
7,Multiple Lines,Whether the customer has multiple phone lines,object
8,Internet Service,"Type of internet service (DSL, Fiber optic, None)",object
9,Online Security,Whether the customer has online security add-on,object
10,Online Backup,Whether the customer has online backup add-on,object
11,Device Protection,Whether the customer has device protection add-on,object
12,Tech Support,Whether the customer has tech support add-on,object
13,Streaming TV,Whether the customer streams TV through the co...,object
14,Streaming Movies,Whether the customer streams movies through th...,object
15,Contract Type,"Contract duration (Month-to-month, One year, T...",object
16,Paperless Billing,Whether the customer receives electronic invoices,object
17,Payment Method,How the customer pays the bill,object
18,Monthly Charges,Amount charged to the customer every month,float64
19,Total Charges,Total amount charged to the customer over time,object
20,Attrition,Whether the customer left the company (target ...,object

In [10]:
data_dictionary.to_excel("data_dictionary.xlsx", index=False)
print("File salvato")

File salvato

In [ ]:
import os
print(os.getcwd())